map_gen: add refbox and wait pos features
carologistics/mps-map-gen pull request #1
Opened 2024-04-14 22:11 UTC by TarikViehmann

2024-04-15 16:01 UTC, snoato requested changes, later dismissed

2024-04-15 16:01 UTC, snoato commented on include/mps_map_gen/mps.hpp
> +  // TODO: CONFIG
todo solved? or do you mean you want to put this into a config file?

2024-04-15 16:01 UTC, snoato commented on include/mps_map_gen/mps.hpp
> +  int field_width = 0;
should the default be a default field?

2024-04-15 16:01 UTC, snoato commented on include/mps_map_gen/mps_map_gen.hpp
>    std::string mps_names[14] = {"M-BS",  "M-SS",  "M-DS",  "M-CS1", "M-CS2",
maybe can move this to config too down the line but okay for now

2024-04-15 16:01 UTC, snoato commented on include/mps_map_gen/waiting_positions.hpp
> +           // 0°
ouchie my formatter hurts

2024-04-15 16:01 UTC, snoato commented on launch/mps_map_gen.launch.py
> +    # resolution = LaunchConfiguration('resolution', default=0.05)
why is this commented out? do we not use it?

2024-04-15 16:01 UTC, snoato commented on src/mps_map_gen.cpp
> +    RCLCPP_INFO(get_logger(), "ACTSCHUALLY");
huhm huhm

2024-04-15 16:01 UTC, snoato commented on src/waiting_positions.cpp
> +        mps.name_ + "-O-WAIT",
KONSISTENZY

2024-04-23 13:25 UTC, TarikViehmann commented on include/mps_map_gen/mps_map_gen.hpp
>    std::string mps_names[14] = {"M-BS",  "M-SS",  "M-DS",  "M-CS1", "M-CS2",
yea could be a future option, but these names are only used for the alternative mode for static transform publishing anyways.

2024-04-23 13:25 UTC, TarikViehmann commented on include/mps_map_gen/mps.hpp
> +  int field_width = 0;
this is now set via ros2 parameter retrieval

2024-04-23 13:28 UTC, TarikViehmann commented on include/mps_map_gen/mps.hpp
> +  // TODO: CONFIG
that was a useles TODO; these values are the actual measurements of the mps, no need to configure them.

2024-05-30 08:53 UTC, techtasie approved these changes
Looking good to me :+1: No complaints from my side!

2024-05-30 08:53 UTC, techtasie commented
@TarikViehmann you should merge if you think it's ready

2024-06-14 17:08 UTC, merged